<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="UseCases\Task\GetAll\" />
    <Folder Include="UseCases\Task\GetById\" />
    <Folder Include="UseCases\Task\Delete\" />
    <Folder Include="UseCases\Task\Uptade\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleTaskManager.Communication\SimpleTaskManager.Communication.csproj" />
  </ItemGroup>

</Project>
